### ISSUE TITLE
Stripe JS should be dynamically loaded as opposed to statically included

### ISSUE THREAD

**Issue by chrisbeach** [chrisbeach/discourse-donations#3]
As per https://stripe.com/docs/stripe-js/reference#including-stripejs

    However you’re using Stripe.js, you always begin by including the library 
    and setting your API key. To get started, include this script on your pages—
    it should always be loaded directly from https://js.stripe.com:

**Comment by angusmcleod** [comment]
@chrisbeach Yes, you're right. It seems they want it loaded on every page to help protect against fraud.

> To best leverage Stripe’s advanced fraud functionality, include this script on every page of your site, not just the checkout page. This allows Stripe to detect anomalous behavior that may be indicative of fraud as customers browse your website.

**Comment by angusmcleod** [comment]
I've removed it from the build taking us back to the status quo ante.

https://github.com/chrisbeach/discourse-donations/commit/c22ef46224256d8c7aff278205c538d77b5763bd

Let's load it in a rails view though rather than requiring the end user to include it via site customizations. I'll make a PR for that.

**Comment by angusmcleod** [comment]
@chrisbeach PR: https://github.com/chrisbeach/discourse-donations/pull/4
